name: Unregister PR preview

on:
  pull_request:
    types: [closed]

jobs:
  pr-preview:
    name: Unregister PR preview
    runs-on: ubuntu-latest

    steps:
      - name: Generate PR preview ID
        id: generate-pr-preview-id
        run: |
          echo "::set-output name=pr-preview-id::$(echo -n \"${{ github.event.organization.login }}${{ github.event.repository.name }}${{ github.event.number }}\" | sha256sum | cut -d " " -f 1 | head -c 7)"
      - name: Unregister PR preview
        uses: spacelift-io/update-file-action@v1.0.0
        with:
          github-token: ${{ secrets.PR_PREVIEW_GH_TOKEN }}
          owner: spacelift-jmf
          repository: spacelift-pr-previews
          commit-message: "Unregister PR preview ${{ steps.generate-pr-preview-id.outputs.pr-preview-id }}"
          target-file-path: "manager/monitored-stacks/simple-example/preview-stacks/${{ github.event.organization.login }}-${{ github.event.repository.name }}-${{ github.event.number }}-${{ steps.generate-pr-preview-id.outputs.pr-preview-id }}.tf"
          delete: true
